# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-utils
  description: Utility functions for use with Terraform in the AWS environment
  homepage: https://cloudposse.com/accelerate
  topics: ""


